### ISSUE TITLE
Running into errors when trying to store a Principal

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/stable-structures#10]
![image](https://user-images.githubusercontent.com/7412443/194898676-e38cf9df-ff5e-4f14-9dce-7e884fbecd86.png)

Basically, this:
> the trait `Storable` is not implemented for `candid::Principal`

Thoughts on how to resolve this?

@ielashi

**Comment by ielashi** [comment]
For a type to be stored in a stable `BTreeMap`, it needs to implement the `Storable` trait. In this case, because `Principal` is a type defined in an external crate, you'll need to wrap it and implement `Storable` on that wrapper:

```
struct StablePrincipal(Principal);

impl Storable for StablePrincipal {
  // implement the storable trait for Principal.
}
```

and then you can use `StablePrincipal` as a key/value `BTreeMap.

And, for future reference, if you have questions please post them on the forum, as then more people will be able to help. I'd file an issue here only in the case of a bug report or a feature request.

**Comment by saikatdas0790** [comment]
@ielashi Thank you.

I usually post on the forum if it's a question. I believed this was a bug, hence reported here :)

I will close this.
