### ISSUE TITLE
What's 4 in post_upgrade and should we have a constant for it?

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/stable-structures#104]
In the "quick start" example, `4` is used to read the state bytes on [post_upgrade](https://github.com/dfinity/stable-structures/blob/76e749f8117d1d10c07dff0f95c00ee2c43e62e0/examples/src/quick_start/src/lib.rs#L88).

Is this a constant related to the "quick start" constant or is it a general constant?
If general, should the library / crate expose such a constant so that developers do not have to hardcode `4`?

**Comment by peterpeterparker** [comment]
@bitdivine thanks but, I'm still confuse. So, in a real world example, one that has a canister that already store some data on the heap - i.e. one that develop a canister that stores data both on the heap and into stable structures - should also start reading with a `4` bytes offset or another dynamic offset? and if dynamic, how to know it?

**Comment by ielashi** [comment]
Here's how I think about:

1. The `MemoryManager` gives you virtual memories that you can use in any way you like. They are not in any way coupled with the concept of stable structures or the heap.
2. When using stable structures, you simply pass these memories to the structures and the internals of the structure use the memory as needed.
3. When using a memory to store data from the heap, it's entirely up to you how you want to store it. In the example above, we first serialize the state in the `pre_upgrade`, then deserialize it in `post_upgrade`. However, we need to store how big the data is so that we know how many bytes to read. The length of the data here is `u32`, which is 4 bytes and we store it in the first 4 bytes of that memory.

Does that make sense? Happy to jump on a call and explain it further as well.

**Comment by peterpeterparker** [comment]
> The length of the data here is u32, which is 4 bytes and we store it in the first 4 bytes of that memory.

AH got it, that it what was unclear to me by reading the code.

I understood the `pre_upgrade`

```
let len = state_bytes.len() as u32; // <--- that was clear
```

But couldn't connect the dot why in `post_upgrade` the example hardcode `4`:

```
// Read the length of the state bytes.
let mut state_len_bytes = [0; 4];
...
memory.read(4, &mut state_bytes);
```

Is there a native Rust way using `u32` to get that `4` value?

If not, maybe we can just improve a bit the comment in the example?

```
// Retrieve the length of the serialized bytes written during pre_upgrade.
```

I did not got it probably because I'm a noob but, maybe I'm not the only one. Happy to provide a PR to improve the comment if it makes sense and if we go that way.

**Comment by ielashi** [comment]
Would you find this change more readable?

```
-    let mut state_len_bytes = [0; 4];
+    let mut state_len_bytes = [0; core::mem::size_of::<u32>()];
```

Yes, feel free to add clarifying comments or include the above change if it's helpful :)

**Comment by ielashi** [comment]
If you don't mind, I'll be closing this ticket now that the original question has been answered.

**Comment by peterpeterparker** [comment]
> Would you find this change more readable?

If shortened:

```
let mut state_len_bytes = [0; size_of::<u32>()];
```

Yes, definitely.

But sure no worries, all good. Thanks for the answers 👍.
